name: NGINX CI/CD

on:
  push:
    paths: ['index.html']
  pull_request:
    paths: ['index.html']

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Start NGINX
      run: |
        docker run -d -p 9889:80 \
          -v $PWD/index.html:/usr/share/nginx/html/index.html \
          --name nginx-ci nginx:1.21-alpine
        sleep 3
    
    - name: Verify deployment
      run: |
        # Test HTTP status
        curl -f http://localhost:9889 || exit 1
        
        # Test content
        LOCAL_HASH=$(md5sum index.html | cut -d' ' -f1)
        REMOTE_HASH=$(curl -s http://localhost:9889 | md5sum | cut -d' ' -f1)
        test "$LOCAL_HASH" = "$REMOTE_HASH" || exit 1
        
        echo "✅ All tests passed!"
    
    - name: Cleanup
      if: always()
      run: docker rm -f nginx-ci
