name: NGINX CI/CD Pipeline

on:
  push:
    paths:
      - 'index.html'
    branches: [ main, master ]
  pull_request:
    paths:
      - 'index.html'
    branches: [ main, master ]

jobs:
  test_nginx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run NGINX container
      run: |
        docker run -d --name nginx-test-${{ github.run_id }} \
          -p 9889:80 \
          -v $(pwd)/index.html:/usr/share/nginx/html/index.html \
          nginx:1.21-alpine
        sleep 5
    
    - name: Test HTTP response code
      run: |
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9889)
        echo "HTTP Response Code: $HTTP_CODE"
        if [ "$HTTP_CODE" != "200" ]; then
          echo "ERROR: Expected HTTP 200, got $HTTP_CODE"
          exit 1
        fi
    
    - name: Compare MD5 checksums
      run: |
        LOCAL_MD5=$(md5sum index.html | awk '{print $1}')
        echo "Local file MD5: $LOCAL_MD5"
        
        REMOTE_MD5=$(curl -s http://localhost:9889 | md5sum | awk '{print $1}')
        echo "Remote content MD5: $REMOTE_MD5"
        
        if [ "$LOCAL_MD5" != "$REMOTE_MD5" ]; then
          echo "ERROR: MD5 mismatch!"
          exit 1
        fi
        echo "SUCCESS: MD5 sums match!"
    
    - name: Cleanup containers
      if: always()
      run: |
        docker stop nginx-test-${{ github.run_id }} || true
        docker rm nginx-test-${{ github.run_id }} || true

  notify_email:
    needs: test_nginx
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Send success email
      if: needs.test_nginx.result == 'success'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ✅ Успешный CI/CD пайплайн - ${{ github.repository }}
        body: |
          Pipeline completed successfully!
          
          Repository: ${{ github.repository }}
          Commit: ${{ github.event.head_commit.message }}
          Branch: ${{ github.ref }}
          Author: ${{ github.actor }}
          Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          All tests passed - Контейнер NGINX работает правильно!
        to: ${{ secrets.EMAIL_RECIPIENT }}
        from: GitHub Actions

    - name: Send failure email
      if: needs.test_nginx.result == 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ❌ CI/CD Pipeline Failed - ${{ github.repository }}
        body: |
          Pipeline has failed!
          
          Repository: ${{ github.repository }}
          Commit: ${{ github.event.head_commit.message }}
          Branch: ${{ github.ref }}
          Author: ${{ github.actor }}
          Pipeline URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          Please check the pipeline logs for details.
        to: ${{ secrets.EMAIL_RECIPIENT }}  # ДОБАВЬТЕ ЭТУ СТРОКУ
        from: GitHub Actions
