name: NGINX Telegram CI/CD

on:
  push:
    paths: ['index.html']
    branches: [main]

jobs:
  test_and_notify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 🐳 Запуск и тест NGINX
      run: |
        # Запуск контейнера
        docker run -d --name nginx-temp -p 9889:80 \
          -v $(pwd)/index.html:/usr/share/nginx/html/index.html \
          nginx:1.21-alpine
        sleep 5
        
        # Тесты
        curl -f http://localhost:9889 || exit 1
        LOCAL=$(md5sum index.html | cut -d' ' -f1)
        REMOTE=$(curl -s http://localhost:9889 | md5sum | cut -d' ' -f1)
        [ "$LOCAL" = "$REMOTE" ] || exit 1
        
        # Очистка
        docker rm -f nginx-temp
        
    - name: 📢 TG Успех
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ УСПЕХ: CI/CD пайплайн выполнен! md5 суммы совпадают!
          Репозиторий: ${{ github.repository }}
          Ссылка: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: 📢 TG Ошибка
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ❌ ОШИБКА: CI/CD пайплайн не выполнен! Суммы md5 не совпали!
          Репозиторий: ${{ github.repository }}
          Ссылка: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
